zookeeper:
  replicaCount: 3
  image:
    registry: docker.io
    repository: bitnami/zookeeper
    tag: 3.7.0-debian-10-r0
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

kafka:
  replicaCount: 3
  image:
    registry: docker.io
    repository: bitnami/kafka
    tag: 2.8.0-debian-10-r0
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  configurationOverrides:
    "auto.create.topics.enable": "true"
    "log.retention.hours": "168"
  # externalAccess:
  #   enabled: true
  # service:
  #   type: NodePort
  # autoDiscovery:
  #   enabled: true
  # serviceAccount:
  #   create: true
  # rbac:
  #   create: true

service:
  type: ClusterIP
  port: 9092