apiVersion: apps/v1
kind: Deployment
metadata:
  name: honeypot-producer
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: honeypot-producer
  template:
    metadata:
      labels:
        app: honeypot-producer
    spec:
      containers:
      - name: honeypot-producer
        image: philippt314/honeypot:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cluster:9092"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
